### ISSUE TITLE
setup_django_heroku.sh doesn't check for valid Django project name

### ISSUE THREAD

**Issue by solkaz** [stevenrouk/heroku-django#1]
The bash script doesn't check if a valid Django project name was entered, which if the user didn't do (such as inputting nothing), then the project files aren't generated, but the script will still generate a Heroku app; it probably should instead alert the user and exit the script

**Comment by stevenrouk** [comment]
Good catch. Looks like Django app names have to be valid python package names. From PEP 8:

"Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."

I'll fix this soon!

**Comment by solkaz** [comment]
I've almost made a fix for it that I should have done tonight if you'd like to have a look. 

On November 17, 2016 3:01:12 PM CST, Steven Rouk notifications@github.com wrote:

> Good catch. Looks like Django app names have to be valid python package
> names. From PEP 8:
> 
> "Modules should have short, all-lowercase names. Underscores can be
> used in the module name if it improves readability. Python packages
> should also have short, all-lowercase names, although the use of
> underscores is discouraged."
> 
> I'll fix this soon!
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/stevenrouk/heroku-django/issues/1#issuecomment-261368153

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stevenrouk** [comment]
Sounds great, I'll keep an eye out.

**Comment by solkaz** [comment]
I've made a PR for this [here](https://github.com/stevenrouk/heroku-django/pull/2)

**Comment by stevenrouk** [comment]
Merged pull request and extended it with checking for valid Django project name (all lowercase alpha) and valid Heroku app name (all lowercase alphanum with potential single hyphen separators).
